require("dotenv").config()
const express=require("express")
const path=require("path")
const hbs=require("hbs")
const cookieParser=require("cookie-parser")
require("./db/conn")
const Register=require("./models/register")
const app=express()
const port=process.env.PORT || 3000
const newPath=path.join(__dirname,"../public")
const viewPath=path.join(__dirname,"../templates/views")
const partialPath=path.join(__dirname,"../templates/partials")
const router=require("./models/router")
app.set("view engine","hbs")
app.set("views",viewPath)
app.use(express.json())
app.use(express.urlencoded({extended:false}))
hbs.registerPartials(partialPath)
app.use(express.static(newPath))
app.use(cookieParser())
app.use(router)
app.listen(port,()=>{
    console.log(`server start for ${port}`)
})